# .github/workflows/deduplicate-contributors.yml
name: Deduplicate Contributors

on:
  workflow_dispatch:
    inputs:
      dry_run:
        description: 'Dry run (show what would be merged without making changes)'
        required: false
        default: 'false'

jobs:
  deduplicate:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Install Dependencies
        run: |
          cd .github
          npm install
          
      - name: Deduplicate Contributors
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
          DRY_RUN: ${{ github.event.inputs.dry_run }}
        run: |
          cd .github
          node scripts/deduplicate-contributors.js
