name: Suggest PR Reviewers

on:
  workflow_dispatch:  
  pull_request:
      types: [opened, reopened]

jobs:
  suggest-reviewers:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      pull-requests: write
      issues: write
      repository-projects: read
      # metadata: read
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Install Dependencies
        run: |
          cd .github
          npm install
          
      - name: Generate Reviewer Suggestions
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd .github
          node scripts/suggest-reviewers.js
          
      - name: Output Results
        if: always()
        run: |
          echo "Review analysis completed"
          if [ -f reviewer-suggestions.md ]; then
            echo "Reviewer suggestions generated:"
            cat reviewer-suggestions.md
          fi
